Repository Goorm-Synergy/Synergy-Backend, pull requests merged in 2025-03, with the labels that each got.

#1 Feat/domain
  src/main/java/com/synergy/backend/domain/booth/model/Booth.java
  src/main/java/com/synergy/backend/domain/conference/model/Conference.java
  src/main/java/com/synergy/backend/domain/member/model/Member.java
  src/main/java/com/synergy/backend/domain/member/model/Occupation.java
  src/main/java/com/synergy/backend/domain/member/model/Role.java
  src/main/java/com/synergy/backend/domain/session/model/Session.java
  src/main/java/com/synergy/backend/global/common/BaseEntity.java
Labels: feature

#2 [Feat] 템플릿 추가
  .github/ISSUE_TEMPLATE/-feat--issue-title.md
  .github/ISSUE_TEMPLATE/-fix--issue-title.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: feature

#9 refactor: Restructure Member table schema
  build.gradle
  gradlew
  src/main/java/com/synergy/backend/domain/interest/entity/Interest.java
  src/main/java/com/synergy/backend/domain/interest/entity/MemberInterest.java
  src/main/java/com/synergy/backend/domain/member/api/MemberController.java
  src/main/java/com/synergy/backend/domain/member/api/dto/LoginRequestDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/SignupRequestDto.java
  src/main/java/com/synergy/backend/domain/member/entity/Admin.java
  src/main/java/com/synergy/backend/domain/member/entity/Attendee.java
  src/main/java/com/synergy/backend/domain/member/entity/Member.java
  src/main/java/com/synergy/backend/domain/member/entity/MembershipLevelType.java
  src/main/java/com/synergy/backend/domain/member/entity/OccupationType.java
  src/main/java/com/synergy/backend/domain/member/entity/PositionType.java
  src/main/java/com/synergy/backend/domain/member/entity/Recruiter.java
  src/main/java/com/synergy/backend/domain/member/entity/RoleType.java
  src/main/java/com/synergy/backend/domain/member/exception/ErrorType.java
  src/main/java/com/synergy/backend/domain/member/exception/NotFoundMember.java
  src/main/java/com/synergy/backend/domain/member/model/Member.java
  src/main/java/com/synergy/backend/domain/member/model/Occupation.java
  src/main/java/com/synergy/backend/domain/member/model/Role.java
  src/main/java/com/synergy/backend/domain/member/repository/AdminRepository.java
  src/main/java/com/synergy/backend/domain/member/repository/AttendeeRepository.java
  src/main/java/com/synergy/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/synergy/backend/domain/member/repository/RecruiterRepository.java
  src/main/java/com/synergy/backend/domain/member/service/MemberService.java
  src/main/java/com/synergy/backend/domain/member/service/UserAuthService.java
  src/main/java/com/synergy/backend/domain/techstack/entity/MemberTechStack.java
  src/main/java/com/synergy/backend/domain/techstack/entity/TechStack.java
  src/main/java/com/synergy/backend/global/config/SecurityConfig.java
  src/main/java/com/synergy/backend/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/synergy/backend/global/jwt/JwtProvider.java
  src/main/resources/application.yml
Labels: feature, refactor

#12 fix: Resolve Hibernate mappedBy issue in MemberInterest & Ensure @Sup…
  src/main/java/com/synergy/backend/domain/member/entity/Admin.java
  src/main/java/com/synergy/backend/domain/member/entity/Attendee.java
  src/main/java/com/synergy/backend/domain/member/entity/Member.java
  src/main/java/com/synergy/backend/domain/member/entity/Recruiter.java
  src/main/java/com/synergy/backend/global/common/BaseEntity.java
Labels: fix

#13 feat: 세션 crud 구성
  src/main/java/com/synergy/backend/domain/booth/model/Booth.java
  src/main/java/com/synergy/backend/domain/conference/entity/Conference.java
  src/main/java/com/synergy/backend/domain/conference/entity/TimePeriod.java
  src/main/java/com/synergy/backend/domain/conference/exception/ErrorType.java
  src/main/java/com/synergy/backend/domain/conference/exception/InvalidTimePeriodException.java
  src/main/java/com/synergy/backend/domain/conference/exception/NotFoundConference.java
  src/main/java/com/synergy/backend/domain/conference/model/Conference.java
  src/main/java/com/synergy/backend/domain/conference/repository/ConferenceRepository.java
  src/main/java/com/synergy/backend/domain/member/entity/Attendee.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionController.java
  src/main/java/com/synergy/backend/domain/session/dto/SessionDetailResDto.java
  src/main/java/com/synergy/backend/domain/session/dto/SessionReqDto.java
  src/main/java/com/synergy/backend/domain/session/dto/SessionResDto.java
  src/main/java/com/synergy/backend/domain/session/entity/Session.java
  src/main/java/com/synergy/backend/domain/session/exception/ErrorType.java
  src/main/java/com/synergy/backend/domain/session/exception/NotValidSessionTime.java
  src/main/java/com/synergy/backend/domain/session/repository/SessionRepository.java
  src/main/java/com/synergy/backend/domain/session/service/SessionService.java
  src/main/java/com/synergy/backend/domain/session/service/SessionServiceImpl.java
  src/main/java/com/synergy/backend/domain/session/service/validate/DateTimeValidator.java
  src/test/java/com/synergy/backend/domain/conference/TimePeriodTest.java
Labels: fix, feature

#15 Feat : 컨퍼런스 도메인 및 cu 구현
  src/main/java/com/synergy/backend/domain/conference/api/ConferenceController.java
  src/main/java/com/synergy/backend/domain/conference/dto/requset/ConferenceCreateRequest.java
  src/main/java/com/synergy/backend/domain/conference/dto/requset/ConferenceUpdateRequest.java
  src/main/java/com/synergy/backend/domain/conference/dto/response/ConferenceCreateResponse.java
  src/main/java/com/synergy/backend/domain/conference/dto/response/ConferenceUpdateResponse.java
  src/main/java/com/synergy/backend/domain/conference/entity/Conference.java
  src/main/java/com/synergy/backend/domain/conference/entity/TimePeriod.java
  src/main/java/com/synergy/backend/domain/conference/exception/ErrorType.java
  src/main/java/com/synergy/backend/domain/conference/exception/InvalidLocationException.java
  src/main/java/com/synergy/backend/domain/conference/exception/InvalidNameException.java
  src/main/java/com/synergy/backend/domain/conference/exception/InvalidTimePeriodException.java
  src/main/java/com/synergy/backend/domain/conference/service/ConferenceDetailResponse.java
  src/main/java/com/synergy/backend/domain/conference/service/ConferenceService.java
  src/main/java/com/synergy/backend/domain/conference/service/ConferenceServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/synergy/backend/domain/conference/entity/ConferenceTest.java
  src/test/java/com/synergy/backend/domain/conference/service/ConferenceServiceImplTest.java
Labels: feature

#21 feat: qr 코드 생성 로직 구현
  build.gradle
  src/main/java/com/synergy/backend/domain/qrCode/exception/ErrorType.java
  src/main/java/com/synergy/backend/domain/qrCode/exception/NotGenerateQRCodeException.java
  src/main/java/com/synergy/backend/domain/qrCode/service/QrService.java
  src/test/java/com/synergy/backend/domain/qrCode/service/QrServiceTest.java
Labels: feature

#28 refactor: 세션 도메인 요구사항에 맞게 변경
  .github/pull_request_template.md
  src/main/java/com/synergy/backend/domain/session/dto/SessionReqDto.java
  src/main/java/com/synergy/backend/domain/session/entity/Session.java
  src/main/java/com/synergy/backend/domain/session/service/SessionServiceImpl.java
  src/test/java/com/synergy/backend/domain/session/service/SessionServiceImplTest.java
Labels: refactor

#25 feat: 포인트 도메인 생성
  src/main/java/com/synergy/backend/domain/member/entity/Attendee.java
  src/main/java/com/synergy/backend/domain/member/entity/MembershipLevelType.java
  src/main/java/com/synergy/backend/domain/point/entity/Point.java
  src/main/java/com/synergy/backend/domain/point/entity/PointType.java
  src/main/java/com/synergy/backend/global/common/BaseEntity.java
Labels: feature

#24 refactor : 컨퍼런스 도메인 요구사항에 맞게 변경
  src/main/java/com/synergy/backend/domain/conference/dto/requset/ConferenceCreateRequest.java
  src/main/java/com/synergy/backend/domain/conference/dto/requset/ConferenceUpdateRequest.java
  src/main/java/com/synergy/backend/domain/conference/dto/response/ConferenceUpdateResponse.java
  src/main/java/com/synergy/backend/domain/conference/entity/Conference.java
  src/main/java/com/synergy/backend/domain/conference/entity/InvalidCommonException.java
  src/main/java/com/synergy/backend/domain/conference/entity/InvalidOrganizerException.java
  src/main/java/com/synergy/backend/domain/conference/exception/ErrorType.java
  src/main/java/com/synergy/backend/domain/conference/service/ConferenceServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/synergy/backend/domain/conference/entity/ConferenceTest.java
  src/test/java/com/synergy/backend/domain/conference/service/ConferenceServiceImplTest.java
Labels: feature, refactor

#17 feat : 부스 CRUD 기능 구현
  src/main/java/com/synergy/backend/domain/booth/controller/BoothController.java
  src/main/java/com/synergy/backend/domain/booth/dto/BoothRequestDto.java
  src/main/java/com/synergy/backend/domain/booth/dto/BoothResponseDto.java
  src/main/java/com/synergy/backend/domain/booth/entity/AttendeeBooth.java
  src/main/java/com/synergy/backend/domain/booth/entity/Booth.java
  src/main/java/com/synergy/backend/domain/booth/exception/ErrorType.java
  src/main/java/com/synergy/backend/domain/booth/exception/NotFoundBoothException.java
  src/main/java/com/synergy/backend/domain/booth/repository/AttendeeBoothRepository.java
  src/main/java/com/synergy/backend/domain/booth/repository/BoothRepository.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothService.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothServiceImpl.java
  src/main/java/com/synergy/backend/domain/conference/entity/Conference.java
Labels: feature

#33 chore : appliationyml 환경 변수 설정
  src/main/resources/application.yml
Labels: feature

#31 [Feat] 파일관리 기능구현
  build.gradle
  src/main/java/com/synergy/backend/global/util/file/config/S3Config.java
  src/main/java/com/synergy/backend/global/util/file/dto/FileAccessDto.java
  src/main/java/com/synergy/backend/global/util/file/dto/FileInformationDto.java
  src/main/java/com/synergy/backend/global/util/file/exception/ErrorType.java
  src/main/java/com/synergy/backend/global/util/file/exception/ExternalApiCallException.java
  src/main/java/com/synergy/backend/global/util/file/exception/FileUploadS3Exception.java
  src/main/java/com/synergy/backend/global/util/file/util/FileS3Util.java
  src/main/java/com/synergy/backend/global/util/file/util/FileUtil.java
Labels: feature

#36 Feat/#35/querydsl 라이브러리 추가
  .github/pull_request_template.md
  build.gradle
  src/main/java/com/synergy/backend/global/config/QuerydslConfig.java
Labels: feature, refactor

#30 feat : 부스 생성 시 QR 생성
  src/main/java/com/synergy/backend/domain/booth/dto/BoothResponseDto.java
  src/main/java/com/synergy/backend/domain/booth/entity/Booth.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothServiceImpl.java
Labels: feature

#37 feat: spring security jwt 기반 인증
  .gitignore
  build.gradle
  src/main/java/com/synergy/backend/SynergyBackendApplication.java
  src/main/java/com/synergy/backend/domain/interest/entity/MemberInterest.java
  src/main/java/com/synergy/backend/domain/interest/repository/InterestRepository.java
  src/main/java/com/synergy/backend/domain/interest/repository/MemberInterestRepository.java
  src/main/java/com/synergy/backend/domain/member/api/AttendeeController.java
  src/main/java/com/synergy/backend/domain/member/api/AuthController.java
  src/main/java/com/synergy/backend/domain/member/api/MemberController.java
  src/main/java/com/synergy/backend/domain/member/api/dto/LoginRequestDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/SignupRequestDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/request/InterestRequestDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/request/LoginAdminRequestDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/request/LoginAttendeeRequestDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/request/SignupAttendeeRequestDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/InterestResponseDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/SignupAttendeeResponseDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/TokenResponseDto.java
  src/main/java/com/synergy/backend/domain/member/entity/Admin.java
  src/main/java/com/synergy/backend/domain/member/entity/Attendee.java
  src/main/java/com/synergy/backend/domain/member/entity/Recruiter.java
  src/main/java/com/synergy/backend/domain/member/entity/RoleType.java
  src/main/java/com/synergy/backend/domain/member/exception/AccessDeniedException.java
  src/main/java/com/synergy/backend/domain/member/exception/AdminOrRecruiterNotFoundException.java
  src/main/java/com/synergy/backend/domain/member/exception/DuplicateEmailException.java
  src/main/java/com/synergy/backend/domain/member/exception/ErrorType.java
  src/main/java/com/synergy/backend/domain/member/exception/InvalidAuthCodeException.java
  src/main/java/com/synergy/backend/domain/member/exception/NotFoundUserException.java
  src/main/java/com/synergy/backend/domain/member/exception/UnauthorizedException.java
  src/main/java/com/synergy/backend/domain/member/repository/AdminRepository.java
  src/main/java/com/synergy/backend/domain/member/repository/AttendeeRepository.java
  src/main/java/com/synergy/backend/domain/member/repository/RecruiterRepository.java
  src/main/java/com/synergy/backend/domain/member/service/AttendeeService.java
  src/main/java/com/synergy/backend/domain/member/service/AttendeeServiceImpl.java
  src/main/java/com/synergy/backend/domain/member/service/AuthService.java
  src/main/java/com/synergy/backend/domain/member/service/AuthServiceImpl.java
  src/main/java/com/synergy/backend/domain/member/service/MemberService.java
  src/main/java/com/synergy/backend/domain/member/service/UserAuthService.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionController.java
  src/main/java/com/synergy/backend/global/common/ApiResponseAdvice.java
  src/main/java/com/synergy/backend/global/config/SecurityConfig.java
  src/main/java/com/synergy/backend/global/config/SwaggerConfig.java
  src/main/java/com/synergy/backend/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/synergy/backend/global/jwt/JwtProvider.java
  src/main/java/com/synergy/backend/global/security/CustomUserDetails.java
  src/main/java/com/synergy/backend/global/security/CustomUserDetailsService.java
  src/main/java/com/synergy/backend/global/security/JwtAuthenticationFilter.java
  src/main/java/com/synergy/backend/global/security/JwtProvider.java
  src/main/java/com/synergy/backend/global/security/exception/ErrorType.java
  src/main/java/com/synergy/backend/global/security/exception/UnKnownUserTypeException.java
  src/main/resources/application.yml
  src/test/java/com/synergy/backend/domain/member/service/AuthServiceImplTest.java
  src/test/java/com/synergy/backend/global/security/CustomUserDetailsServiceTest.java
  src/test/java/com/synergy/backend/global/security/JwtProviderTest.java
Labels: feature, refactor

#40 Test/#39/파일기능 테스트구현
  src/main/java/com/synergy/backend/global/util/file/util/FileS3Util.java
  src/test/java/com/synergy/backend/global/util/file/util/FileS3UtilTest.java
Labels: style, test

#44 fix : test환경 applicatication yml 인식불가 해결 및 테스트 환경 분리
  build.gradle
  src/main/resources/application.yml
  src/test/java/com/synergy/backend/domain/conference/service/ConferenceServiceImplTest.java
  src/test/java/com/synergy/backend/global/util/file/util/FileS3UtilTest.java
Labels: fix, style

#43 feat: 포인트 기능 구현
  .DS_Store
  .gitignore
  src/main/java/com/synergy/backend/domain/member/entity/Attendee.java
  src/main/java/com/synergy/backend/domain/member/exception/ErrorType.java
  src/main/java/com/synergy/backend/domain/member/exception/NotFoundRecruiterException.java
  src/main/java/com/synergy/backend/domain/member/exception/NotFoundUserException.java
  src/main/java/com/synergy/backend/domain/member/service/AuthServiceImpl.java
  src/main/java/com/synergy/backend/domain/point/api/PointController.java
  src/main/java/com/synergy/backend/domain/point/api/dto/PointResponseDto.java
  src/main/java/com/synergy/backend/domain/point/entity/Point.java
  src/main/java/com/synergy/backend/domain/point/exception/ErrorType.java
  src/main/java/com/synergy/backend/domain/point/exception/PointNotFoundException.java
  src/main/java/com/synergy/backend/domain/point/repository/PointRepository.java
  src/main/java/com/synergy/backend/domain/point/service/PointService.java
  src/main/java/com/synergy/backend/domain/point/service/PointServiceImpl.java
  src/test/java/com/synergy/backend/domain/member/service/AuthServiceImplTest.java
  src/test/java/com/synergy/backend/domain/point/service/PointServiceImplTest.java
Labels: feature

#47 test : booth 도메인 테스트코드 추가
  src/test/java/com/synergy/backend/domain/booth/entity/BoothTest.java
  src/test/java/com/synergy/backend/domain/booth/service/BoothServiceImplTest.java
Labels: test

#54 test : 컨퍼런스 컨트롤러 테스트 구현 (컨퍼런스 등록 API)
  build.gradle
  src/main/java/com/synergy/backend/SynergyBackendApplication.java
  src/main/java/com/synergy/backend/domain/conference/api/ConferenceController.java
  src/main/java/com/synergy/backend/domain/conference/service/ConferenceServiceImpl.java
  src/main/java/com/synergy/backend/global/CurrentUser.java
  src/main/java/com/synergy/backend/global/config/JpaAuditingConfig.java
  src/test/java/com/synergy/backend/domain/conference/api/ConferenceControllerTest.java
Labels: fix, test

#41 feat: 세션 QnA기능 구현
  src/main/java/com/synergy/backend/domain/booth/dto/BoothRequestDto.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothServiceImpl.java
  src/main/java/com/synergy/backend/domain/member/entity/Attendee.java
  src/main/java/com/synergy/backend/domain/point/service/PointServiceImpl.java
  src/main/java/com/synergy/backend/domain/qrCode/service/QrService.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionController.java
  src/main/java/com/synergy/backend/domain/session/dto/SessionDetailResDto.java
  src/main/java/com/synergy/backend/domain/session/dto/SessionReqDto.java
  src/main/java/com/synergy/backend/domain/session/dto/questionDto/QuestionReqDto.java
  src/main/java/com/synergy/backend/domain/session/dto/questionDto/QuestionResDto.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionDto/SessionDetailResDto.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionDto/SessionReqDto.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionDto/SessionResDto.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionparticipateDto/SessionParticipateRateDetailResDto.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionparticipateDto/SessionParticipateRateResDto.java
  src/main/java/com/synergy/backend/domain/session/entity/AttendeeSession.java
  src/main/java/com/synergy/backend/domain/session/entity/Session.java
  src/main/java/com/synergy/backend/domain/session/entity/SessionQuestion.java
  src/main/java/com/synergy/backend/domain/session/exception/DecodingException.java
  src/main/java/com/synergy/backend/domain/session/exception/ErrorType.java
  src/main/java/com/synergy/backend/domain/session/exception/InvalidTimeException.java
  src/main/java/com/synergy/backend/domain/session/exception/NotAttendedSession.java
  src/main/java/com/synergy/backend/domain/session/exception/NotFoundSession.java
  src/main/java/com/synergy/backend/domain/session/exception/NotMatchedAttendeeCodeException.java
  src/main/java/com/synergy/backend/domain/session/exception/NotValidSessionTime.java
  src/main/java/com/synergy/backend/domain/session/repository/AttendeeSessionRepository.java
  src/main/java/com/synergy/backend/domain/session/repository/sessionQuestionRepository/SessionQuestionCustomRepository.java
  src/main/java/com/synergy/backend/domain/session/repository/sessionQuestionRepository/SessionQuestionCustomRepositoryImpl.java
  src/main/java/com/synergy/backend/domain/session/repository/sessionQuestionRepository/SessionQuestionRepository.java
  src/main/java/com/synergy/backend/domain/session/repository/sessionRepository/SessionCustomRepository.java
  src/main/java/com/synergy/backend/domain/session/repository/sessionRepository/SessionCustomRepositoryImpl.java
  src/main/java/com/synergy/backend/domain/session/repository/sessionRepository/SessionRepository.java
  src/main/java/com/synergy/backend/domain/session/service/SessionParticipateService.java
  src/main/java/com/synergy/backend/domain/session/service/SessionParticipateServiceImpl.java
  src/main/java/com/synergy/backend/domain/session/service/SessionService.java
  src/main/java/com/synergy/backend/domain/session/service/SessionServiceImpl.java
  src/main/java/com/synergy/backend/global/config/SecurityConfig.java
  src/main/java/com/synergy/backend/global/exception/AuthorizedException.java
  src/main/java/com/synergy/backend/global/exception/ErrorType.java
  src/main/java/com/synergy/backend/global/util/SecurityUtil.java
  src/test/java/com/synergy/backend/domain/point/service/PointServiceImplTest.java
  src/test/java/com/synergy/backend/domain/qrCode/service/QrServiceTest.java
Labels: fix, feature, refactor

#58 feat: QR코드 S3에 저장 로직 구현
  src/main/java/com/synergy/backend/domain/member/entity/Attendee.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionDto/SessionDetailResDto.java
  src/main/java/com/synergy/backend/domain/session/entity/Session.java
  src/main/java/com/synergy/backend/domain/session/service/SessionServiceImpl.java
  src/main/java/com/synergy/backend/global/util/file/util/FileS3Util.java
  src/main/java/com/synergy/backend/global/util/file/util/FileUtil.java
Labels: fix, feature

#61 fix : BoothServiceImplTest 오류 수정
  src/test/java/com/synergy/backend/domain/booth/service/BoothServiceImplTest.java
Labels: fix

#60 chore : restdocs 설정 및 컨퍼런스 API 문서화
  build.gradle
  src/docs/asciidoc/conference/conference.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/synergy/backend/domain/conference/api/ConferenceController.java
  src/main/java/com/synergy/backend/domain/conference/dto/requset/ConferenceCreateRequest.java
  src/main/java/com/synergy/backend/domain/conference/dto/requset/ConferenceUpdateRequest.java
  src/main/java/com/synergy/backend/domain/conference/dto/response/ConferenceUpdateResponse.java
  src/main/java/com/synergy/backend/domain/conference/service/ConferenceServiceImpl.java
  src/test/java/com/synergy/backend/SynergyBackendApplicationTests.java
  src/test/java/com/synergy/backend/docs/RestDocsSupport.java
  src/test/java/com/synergy/backend/docs/conference/ConferenceControllerDocsTest.java
  src/test/java/com/synergy/backend/domain/booth/service/BoothServiceImplTest.java
  src/test/java/com/synergy/backend/domain/conference/api/ConferenceControllerTest.java
  src/test/java/com/synergy/backend/domain/conference/service/ConferenceServiceImplTest.java
  src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: fix, feature, refactor

#64 feat: 포인트 랭킹
  src/main/java/com/synergy/backend/domain/member/api/AdminController.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/AttendeeLevelRankingResponseDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/AttendeePointRankingResponseDto.java
  src/main/java/com/synergy/backend/domain/member/entity/Attendee.java
  src/main/java/com/synergy/backend/domain/member/repository/AttendeeRepository.java
  src/main/java/com/synergy/backend/domain/member/service/AdminService.java
  src/main/java/com/synergy/backend/domain/member/service/AdminServiceImpl.java
  src/main/java/com/synergy/backend/domain/point/service/PointServiceImpl.java
  src/main/resources/data.sql
  src/test/java/com/synergy/backend/domain/member/service/AdminServiceImplTest.java
Labels: feature

#68 fix: 세션에 대한 사용자 인증 로직 수정
  src/main/java/com/synergy/backend/domain/session/controller/SessionController.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionDashboardController.java
  src/main/java/com/synergy/backend/domain/session/service/SessionParticipateService.java
  src/main/java/com/synergy/backend/domain/session/service/SessionParticipateServiceImpl.java
  src/main/java/com/synergy/backend/domain/session/service/SessionService.java
  src/main/java/com/synergy/backend/domain/session/service/SessionServiceImpl.java
  src/main/java/com/synergy/backend/global/util/SecurityUtils.java
Labels: refactor

#76 chore : 임시 서버 빌드 스크립트 작성
  Dockerfile
  build.sh
  src/main/resources/application.yml
  src/main/resources/static/docs/index.html
Labels: feature

#72 feat: init data 생성
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/MyInfoResponseDto.java
  src/main/java/com/synergy/backend/domain/member/entity/Attendee.java
  src/main/java/com/synergy/backend/domain/member/entity/Recruiter.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: feature

#75 feat : 부스 참석, 부스 참석 취소, 부스 참석자 조회 기능 구현
  src/main/java/com/synergy/backend/domain/booth/controller/BoothController.java
  src/main/java/com/synergy/backend/domain/booth/exception/DuplicateParticipationException.java
  src/main/java/com/synergy/backend/domain/booth/exception/ErrorType.java
  src/main/java/com/synergy/backend/domain/booth/exception/NotFoundParticipationException.java
  src/main/java/com/synergy/backend/domain/booth/repository/AttendeeBoothRepository.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothParticipationService.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothParticipationServiceImpl.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothService.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothServiceImpl.java
Labels: feature

#81 feat: 세션별 상세 정보 조회 기능 구현
  src/main/java/com/synergy/backend/domain/member/repository/AdminRepository.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionController.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionDashboardController.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionDto/SessionReqDto.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionparticipateDto/SessionParticipateRateDetailResDto.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionparticipateDto/SessionParticipateRateResDto.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionparticipateDto/SessionParticipateTechResDto.java
  src/main/java/com/synergy/backend/domain/session/entity/Session.java
  src/main/java/com/synergy/backend/domain/session/repository/sessionRepository/SessionCustomRepository.java
  src/main/java/com/synergy/backend/domain/session/repository/sessionRepository/SessionCustomRepositoryImpl.java
  src/main/java/com/synergy/backend/domain/session/repository/sessionRepository/SessionRepository.java
  src/main/java/com/synergy/backend/domain/session/service/SessionParticipateServiceImpl.java
  src/main/java/com/synergy/backend/domain/session/service/SessionService.java
  src/main/java/com/synergy/backend/domain/session/service/SessionServiceImpl.java
  src/main/java/com/synergy/backend/global/util/file/util/FileS3Util.java
  src/main/java/com/synergy/backend/global/util/file/util/FileUtil.java
  src/main/resources/data.sql
Labels: fix, feature, refactor

#80 feat : Cors 허용 및 rest docs 경로 허용
  src/main/java/com/synergy/backend/global/config/SecurityConfig.java
Labels: feature

#88 feat : 채용담당자 기능 - 사용자 상세 조회, 사용자 페이징 조회 구현
  src/main/java/com/synergy/backend/domain/member/api/RecruiterController.java
  src/main/java/com/synergy/backend/domain/member/api/dto/AttendeeFilterRequest.java
  src/main/java/com/synergy/backend/domain/member/api/dto/AttendeeListResponse.java
  src/main/java/com/synergy/backend/domain/member/api/dto/AttendeeSimpleResponseDto.java
  src/main/java/com/synergy/backend/domain/member/exception/ErrorType.java
  src/main/java/com/synergy/backend/domain/member/exception/ForbiddenAccessAttendee.java
  src/main/java/com/synergy/backend/domain/member/repository/AttendeeRepository.java
  src/main/java/com/synergy/backend/domain/member/repository/AttendeeRepositoryCustom.java
  src/main/java/com/synergy/backend/domain/member/repository/AttendeeRepositoryImpl.java
  src/main/java/com/synergy/backend/domain/member/service/AttendeeDetailResponse.java
  src/main/java/com/synergy/backend/domain/member/service/RecruiterService.java
  src/main/java/com/synergy/backend/domain/member/service/RecruiterServiceImpl.java
  src/main/resources/data.sql
Labels: feature

#92 fix : Attendee 변경으로 인한 data.sql / 관련 코드 수정(컴파일 에러)
  src/main/java/com/synergy/backend/domain/member/repository/AttendeeRepository.java
  src/main/java/com/synergy/backend/domain/member/repository/AttendeeRepositoryImpl.java
  src/main/java/com/synergy/backend/domain/member/service/AttendeeDetailResponse.java
  src/main/resources/data.sql
  src/main/resources/static/docs/index.html
Labels: fix, feature

#97 feat: cicd 템플릿 구현
  .github/workflows/CI-CD.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/java/com/synergy/backend/domain/session/service/SessionServiceImpl.java
  src/main/resources/application.yml
Labels: feature

#91 fix: securityfilter 설정
  src/main/java/com/synergy/backend/domain/booth/controller/BoothController.java
  src/main/java/com/synergy/backend/domain/booth/controller/BoothVerifyController.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionController.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionVerifyController.java
  src/main/java/com/synergy/backend/global/config/SecurityConfig.java
  src/test/java/com/synergy/backend/domain/booth/service/BoothServiceImplTest.java
Labels: feature

#94 feat: refresh token 기능 추가
  src/main/java/com/synergy/backend/domain/conference/api/ConferenceController.java
  src/main/java/com/synergy/backend/domain/member/api/AuthController.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/TokenResponseDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/TokenWithRefreshToken.java
  src/main/java/com/synergy/backend/domain/member/entity/Admin.java
  src/main/java/com/synergy/backend/domain/member/entity/Attendee.java
  src/main/java/com/synergy/backend/domain/member/entity/Recruiter.java
  src/main/java/com/synergy/backend/domain/member/entity/User.java
  src/main/java/com/synergy/backend/domain/member/service/AuthService.java
  src/main/java/com/synergy/backend/domain/member/service/AuthServiceImpl.java
  src/main/java/com/synergy/backend/domain/session/service/SessionParticipateServiceImpl.java
  src/main/java/com/synergy/backend/domain/session/service/SessionServiceImpl.java
  src/main/java/com/synergy/backend/global/common/ApiResponse.java
  src/main/java/com/synergy/backend/global/config/JwtConfig.java
  src/main/java/com/synergy/backend/global/config/MailConfig.java
  src/main/java/com/synergy/backend/global/config/SecurityConfig.java
  src/main/java/com/synergy/backend/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/synergy/backend/global/jwt/JwtProperties.java
  src/main/java/com/synergy/backend/global/jwt/JwtProvider.java
  src/main/java/com/synergy/backend/global/mail/MailProperties.java
  src/main/java/com/synergy/backend/global/mail/MailServiceImpl.java
  src/main/java/com/synergy/backend/global/security/CurrentUser.java
  src/main/java/com/synergy/backend/global/security/CustomUserDetails.java
  src/main/java/com/synergy/backend/global/security/JwtProvider.java
  src/main/java/com/synergy/backend/global/security/SecurityUtils.java
  src/main/java/com/synergy/backend/global/token/CookieUtils.java
  src/main/java/com/synergy/backend/global/token/TokenService.java
  src/main/java/com/synergy/backend/global/token/TokenServiceImpl.java
  src/main/java/com/synergy/backend/global/token/exception/ErrorType.java
  src/main/java/com/synergy/backend/global/token/exception/InvalidRefreshTokenException.java
  src/main/resources/application.yml
  src/test/java/com/synergy/backend/domain/booth/service/BoothServiceImplTest.java
  src/test/java/com/synergy/backend/domain/conference/api/ConferenceControllerTest.java
  src/test/java/com/synergy/backend/domain/member/service/AuthServiceImplTest.java
  src/test/java/com/synergy/backend/global/mail/MailServiceImplTest.java
  src/test/java/com/synergy/backend/global/security/JwtProviderTest.java
  src/test/java/com/synergy/backend/global/token/TokenServiceImplTest.java
Labels: feature, refactor, test

#98 feat: swagger configuration
  src/main/java/com/synergy/backend/domain/booth/controller/BoothController.java
  src/main/java/com/synergy/backend/domain/conference/api/ConferenceController.java
  src/main/java/com/synergy/backend/domain/member/api/AdminController.java
  src/main/java/com/synergy/backend/domain/member/api/AttendeeController.java
  src/main/java/com/synergy/backend/domain/member/api/AuthController.java
  src/main/java/com/synergy/backend/domain/member/api/RecruiterController.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/AttendeeBaseInfoResponseDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/AttendeeDetailInfoResponseDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/AttendeeFullInfoResponseDto.java
  src/main/java/com/synergy/backend/domain/point/api/PointController.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionController.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionDashboardController.java
  src/main/java/com/synergy/backend/global/annotation/DisableSwaggerSecurity.java
  src/main/java/com/synergy/backend/global/common/ApiResponse.java
  src/main/java/com/synergy/backend/global/config/SwaggerConfig.java
  src/main/java/com/synergy/backend/global/exception/ExceptionResponse.java
Labels: feature

#103 feat: cicd 템플릿 구현
  .github/workflows/CI-CD.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/java/com/synergy/backend/domain/session/service/SessionServiceImpl.java
  src/main/resources/application.yml
Labels: fix, refactor

#112 feat: 참가자 프로필사진, swagger 문서추가
  src/main/java/com/synergy/backend/domain/booth/controller/BoothController.java
  src/main/java/com/synergy/backend/domain/booth/controller/BoothDashboardController.java
  src/main/java/com/synergy/backend/domain/booth/controller/BoothVerifyController.java
  src/main/java/com/synergy/backend/domain/booth/dto/InterestParticipationDto.java
  src/main/java/com/synergy/backend/domain/booth/entity/Booth.java
  src/main/java/com/synergy/backend/domain/booth/entity/BoothParticipation.java
  src/main/java/com/synergy/backend/domain/booth/repository/BoothParticipationRepository.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothParticipationServiceImpl.java
  src/main/java/com/synergy/backend/domain/conference/api/ConferenceController.java
  src/main/java/com/synergy/backend/domain/member/api/AdminController.java
  src/main/java/com/synergy/backend/domain/member/api/AttendeeController.java
  src/main/java/com/synergy/backend/domain/member/api/AuthController.java
  src/main/java/com/synergy/backend/domain/member/api/RecruiterController.java
  src/main/java/com/synergy/backend/domain/member/api/dto/AttendeeFilterRequest.java
  src/main/java/com/synergy/backend/domain/member/api/dto/AttendeeListResponse.java
  src/main/java/com/synergy/backend/domain/member/api/dto/request/AttendeeFilterRequest.java
  src/main/java/com/synergy/backend/domain/member/api/dto/request/JobInfoDetailsRequestDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/request/LoginAdminRequestDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/request/LoginAttendeeRequestDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/AttendeeBaseInfoResponseDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/AttendeeListResponse.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/AttendeeSimpleResponseDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/MyInfoResponseDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/NextPointResponseDto.java
  src/main/java/com/synergy/backend/domain/member/entity/Attendee.java
  src/main/java/com/synergy/backend/domain/member/entity/details/MembershipLevelType.java
  src/main/java/com/synergy/backend/domain/member/repository/AttendeeRepositoryCustom.java
  src/main/java/com/synergy/backend/domain/member/repository/AttendeeRepositoryImpl.java
  src/main/java/com/synergy/backend/domain/member/service/AttendeeDetailResponse.java
  src/main/java/com/synergy/backend/domain/member/service/AttendeeService.java
  src/main/java/com/synergy/backend/domain/member/service/AttendeeServiceImpl.java
  src/main/java/com/synergy/backend/domain/member/service/AuthService.java
  src/main/java/com/synergy/backend/domain/member/service/AuthServiceImpl.java
  src/main/java/com/synergy/backend/domain/member/service/RecruiterService.java
  src/main/java/com/synergy/backend/domain/member/service/RecruiterServiceImpl.java
  src/main/java/com/synergy/backend/domain/member/vo/NextPointInfo.java
  src/main/java/com/synergy/backend/domain/member/vo/TokenWithRefreshToken.java
  src/main/java/com/synergy/backend/domain/meta/enums/EnumController.java
  src/main/java/com/synergy/backend/domain/meta/enums/EnumResponseDto.java
  src/main/java/com/synergy/backend/domain/meta/enums/EnumType.java
  src/main/java/com/synergy/backend/domain/meta/lookups/LookupController.java
  src/main/java/com/synergy/backend/domain/meta/lookups/LookupResponseDto.java
  src/main/java/com/synergy/backend/domain/meta/lookups/LookupType.java
  src/main/java/com/synergy/backend/domain/point/api/PointController.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionController.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionDashboardController.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionVerifyController.java
  src/main/java/com/synergy/backend/global/annotation/SwaggerSummaryRole.java
  src/main/java/com/synergy/backend/global/config/SecurityConfig.java
  src/main/java/com/synergy/backend/global/config/SwaggerConfig.java
  src/main/resources/data-test.sql
  src/main/resources/data.sql
  src/test/java/com/synergy/backend/domain/member/api/RecruiterControllerTest.java
  src/test/java/com/synergy/backend/domain/member/repository/spring/AttendeeRepositoryTest.java
  src/test/java/com/synergy/backend/domain/member/service/AuthServiceImplTest.java
  src/test/java/com/synergy/backend/domain/member/service/RecruiterServiceImplTest.java
  src/test/java/com/synergy/backend/domain/member/service/spring/RecruiterServiceImplTest.java
Labels: feature

#117 style : Conference API Request body 네이밍 수정
  src/main/java/com/synergy/backend/domain/conference/dto/requset/ConferenceCreateRequest.java
  src/main/java/com/synergy/backend/domain/conference/dto/requset/ConferenceUpdateRequest.java
  src/main/java/com/synergy/backend/domain/conference/service/ConferenceServiceImpl.java
  src/main/resources/static/docs/index.html
  src/test/java/com/synergy/backend/docs/conference/ConferenceControllerDocsTest.java
  src/test/java/com/synergy/backend/domain/conference/api/ConferenceControllerTest.java
Labels: style

#115 feat : 부스 생성 시 이미지 첨부, QR코드 생성
  src/main/java/com/synergy/backend/domain/booth/controller/BoothController.java
  src/main/java/com/synergy/backend/domain/booth/dto/BoothRequestDto.java
  src/main/java/com/synergy/backend/domain/booth/dto/BoothResponseDto.java
  src/main/java/com/synergy/backend/domain/booth/entity/Booth.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothService.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothServiceImpl.java
  src/main/resources/data-test.sql
  src/main/resources/data.sql
  src/test/java/com/synergy/backend/domain/booth/entity/BoothTest.java
  src/test/java/com/synergy/backend/domain/booth/service/BoothServiceImplTest.java
Labels: feature

#121 feat: add id and rename
  src/main/java/com/synergy/backend/domain/meta/enums/EnumResponseDto.java
  src/main/java/com/synergy/backend/domain/meta/lookups/LookupController.java
  src/main/java/com/synergy/backend/domain/meta/lookups/LookupResponseDto.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionController.java
Labels: feature

#118 feat: 실제이미지url추가
  src/main/java/com/synergy/backend/domain/member/entity/Attendee.java
  src/main/resources/data.sql
Labels: feature

#122 fix: 세션 api 수정
  src/main/java/com/synergy/backend/domain/member/service/AuthServiceImpl.java
  src/main/java/com/synergy/backend/domain/qrCode/service/QrService.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionController.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionVerifyController.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionDto/SessionDetailResDto.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionDto/SessionReqDto.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionDto/SessionResDto.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionparticipateDto/SessionParticipateRateDetailResDto.java
  src/main/java/com/synergy/backend/domain/session/entity/Session.java
  src/main/java/com/synergy/backend/domain/session/entity/SessionQuestion.java
  src/main/java/com/synergy/backend/domain/session/repository/sessionRepository/SessionRepository.java
  src/main/java/com/synergy/backend/domain/session/service/SessionParticipateService.java
  src/main/java/com/synergy/backend/domain/session/service/SessionParticipateServiceImpl.java
  src/main/java/com/synergy/backend/domain/session/service/SessionServiceImpl.java
  src/main/java/com/synergy/backend/global/util/file/util/FileS3Util.java
  src/main/resources/application.yml
  src/test/java/com/synergy/backend/domain/session/entity/SessionTest.java
Labels: fix

#127 fix : booth function modify(부스 기능 버그 수정 및 구현)
  src/main/java/com/synergy/backend/domain/booth/controller/BoothController.java
  src/main/java/com/synergy/backend/domain/booth/controller/BoothDashboardController.java
  src/main/java/com/synergy/backend/domain/booth/controller/BoothVerifyController.java
  src/main/java/com/synergy/backend/domain/booth/dto/BoothDetailResponseDto.java
  src/main/java/com/synergy/backend/domain/booth/dto/BoothParticipateInterestedTechDto.java
  src/main/java/com/synergy/backend/domain/booth/dto/BoothParticipationResponseDto.java
  src/main/java/com/synergy/backend/domain/booth/dto/BoothRequestDto.java
  src/main/java/com/synergy/backend/domain/booth/dto/BoothResponseDto.java
  src/main/java/com/synergy/backend/domain/booth/dto/InterestParticipationDto.java
  src/main/java/com/synergy/backend/domain/booth/entity/Booth.java
  src/main/java/com/synergy/backend/domain/booth/repository/BoothParticipationRepository.java
  src/main/java/com/synergy/backend/domain/booth/repository/BoothRepository.java
  src/main/java/com/synergy/backend/domain/booth/repository/querydsl/BoothRepositoryCustom.java
  src/main/java/com/synergy/backend/domain/booth/repository/querydsl/BoothRepositoryImpl.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothParticipationService.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothParticipationServiceImpl.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothService.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothServiceImpl.java
  src/main/resources/data-test.sql
  src/main/resources/data.sql
  src/main/resources/static/docs/index.html
  src/test/java/com/synergy/backend/domain/booth/entity/BoothTest.java
  src/test/java/com/synergy/backend/domain/booth/service/BoothServiceImplTest.java
Labels: fix, feature, test

#128 feat: 로그아웃 및 리팩토링
  src/docs/plantuml/admin/AdminAttendeeRanking.puml
  src/docs/plantuml/attendee/OnBoarding.puml
  src/docs/plantuml/auth/EmailVerification.puml
  src/docs/plantuml/auth/LoginAsAdminRecruiter.puml
  src/docs/plantuml/auth/LoginAsAttendee.puml
  src/docs/plantuml/auth/PasswordReset.puml
  src/docs/plantuml/auth/Signup.puml
  src/docs/plantuml/recruiter/RecruiterLikeAttendee.puml
  src/main/java/com/synergy/backend/domain/member/api/AuthController.java
  src/main/java/com/synergy/backend/domain/member/service/AuthService.java
  src/main/java/com/synergy/backend/domain/member/service/AuthServiceImpl.java
  src/main/java/com/synergy/backend/global/token/CookieUtils.java
  src/test/java/com/synergy/backend/domain/member/service/AuthServiceImplTest.java
  src/test/java/com/synergy/backend/global/token/CookieUtilsTest.java
Labels: feature, refactor, test

#130 fix: qr 코드 로직 수정하기
  src/main/java/com/synergy/backend/domain/booth/controller/BoothController.java
  src/main/java/com/synergy/backend/domain/booth/entity/Booth.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothService.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothServiceImpl.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionController.java
  src/main/java/com/synergy/backend/domain/session/entity/Session.java
  src/main/java/com/synergy/backend/domain/session/service/SessionService.java
  src/main/java/com/synergy/backend/domain/session/service/SessionServiceImpl.java
  src/test/java/com/synergy/backend/domain/booth/entity/BoothTest.java
  src/test/java/com/synergy/backend/domain/booth/service/BoothServiceImplTest.java
Labels: fix

#135 fix : test 해결 및 채용담당자 오류 수정
  src/main/java/com/synergy/backend/domain/booth/service/BoothServiceImpl.java
  src/main/java/com/synergy/backend/domain/member/repository/AttendeeRepositoryImpl.java
  src/main/java/com/synergy/backend/domain/member/service/RecruiterServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/static/docs/index.html
Labels: fix

#133 refactor: 권한 및 인증 관련 에러 핸들링
  src/main/java/com/synergy/backend/domain/booth/entity/Booth.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothService.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothServiceImpl.java
  src/main/java/com/synergy/backend/domain/member/service/AuthServiceImpl.java
  src/main/java/com/synergy/backend/global/config/SecurityConfig.java
  src/main/java/com/synergy/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/synergy/backend/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/synergy/backend/global/jwt/JwtProvider.java
  src/main/java/com/synergy/backend/global/security/CustomAccessDeniedHandler.java
  src/main/java/com/synergy/backend/global/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/synergy/backend/global/security/exception/ErrorType.java
  src/main/java/com/synergy/backend/global/token/exception/ErrorType.java
  src/main/java/com/synergy/backend/global/token/exception/ExpiredRefreshTokenException.java
  src/main/java/com/synergy/backend/global/token/exception/InvalidAccessTokenException.java
  src/main/java/com/synergy/backend/global/token/exception/InvalidRoleClaimException.java
  src/main/java/com/synergy/backend/global/token/exception/MissingRoleClaimException.java
  src/main/resources/data.sql
  src/test/java/com/synergy/backend/domain/conference/api/ConferenceControllerTest.java
  src/test/java/com/synergy/backend/domain/member/api/RecruiterControllerTest.java
  src/test/java/com/synergy/backend/domain/member/service/AuthServiceImplTest.java
  src/test/java/com/synergy/backend/global/security/JwtProviderTest.java
Labels: refactor

#137 fix : Booth 등록 로직/테스트 수정
  src/main/java/com/synergy/backend/domain/booth/service/BoothServiceImpl.java
  src/test/java/com/synergy/backend/domain/booth/service/BoothServiceImplTest.java
Labels: fix, test

#147 Feat : swagger 문서에 들어갈 상세 설명 추가
  src/main/java/com/synergy/backend/domain/booth/controller/BoothDashboardController.java
  src/main/java/com/synergy/backend/domain/booth/controller/BoothVerifyController.java
  src/main/java/com/synergy/backend/domain/booth/dto/BoothRequestDto.java
  src/main/java/com/synergy/backend/domain/conference/dto/requset/ConferenceCreateRequest.java
  src/main/java/com/synergy/backend/domain/conference/dto/requset/ConferenceUpdateRequest.java
  src/main/java/com/synergy/backend/domain/member/api/dto/request/EmailVerificationConfirmDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/request/EmailVerificationRequestDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/request/LoginAdminRequestDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/request/LoginAttendeeRequestDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/request/PasswordResetConfirmDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/request/PasswordResetRequestDto.java
  src/main/java/com/synergy/backend/domain/session/controller/SessionVerifyController.java
  src/main/java/com/synergy/backend/domain/session/dto/questionDto/QuestionReqDto.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionDto/SessionReqDto.java
Labels: feature, style

#142 feat : 테스트 수행 시간 단축, jacoco 추가
  build.gradle
  src/main/resources/data-test.sql
  src/test/java/com/synergy/backend/domain/booth/controller/BoothControllerTest.java
  src/test/java/com/synergy/backend/domain/booth/repository/BoothRepositoryTest.java
  src/test/java/com/synergy/backend/domain/booth/repository/querydsl/BoothRepositoryImplTest.java
  src/test/java/com/synergy/backend/domain/conference/api/ConferenceControllerTest.java
  src/test/java/com/synergy/backend/domain/conference/repository/ConferenceRepositoryTest.java
  src/test/java/com/synergy/backend/domain/conference/service/ConferenceServiceImplTest.java
  src/test/java/com/synergy/backend/domain/member/api/RecruiterControllerTest.java
  src/test/java/com/synergy/backend/domain/member/repository/spring/AttendeeRepositoryTest.java
  src/test/java/com/synergy/backend/domain/member/service/spring/RecruiterServiceImplTest.java
  src/test/java/com/synergy/backend/learning/Learning2Test.java
  src/test/java/com/synergy/backend/learning/Learning3Test.java
  src/test/java/com/synergy/backend/module/ControllerTestSupport.java
  src/test/java/com/synergy/backend/module/IntegrationSupportTest.java
  src/test/java/com/synergy/backend/module/TestExecutionTimeListener.java
  src/test/resources/META-INF/spring.factories
Labels: refactor, test

#150 fix: 세션 조회 기능 수정
  src/main/java/com/synergy/backend/domain/session/dto/sessionDto/SessionDetailResDto.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionparticipateDto/SessionParticipateRateDetailResDto.java
  src/main/java/com/synergy/backend/domain/session/repository/sessionRepository/SessionCustomRepositoryImpl.java
  src/main/java/com/synergy/backend/domain/session/service/SessionParticipateServiceImpl.java
  src/main/java/com/synergy/backend/domain/session/service/SessionServiceImpl.java
  src/main/resources/data.sql
Labels: fix, refactor

#148 refactor: CustomUserDetails 조회 성능개선 및 프로필 수정 기능 추가
  CustomUserDetailsService Test.jmx
  src/main/java/com/synergy/backend/SynergyBackendApplication.java
  src/main/java/com/synergy/backend/domain/member/api/AttendeeController.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/InterestResponseDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/ProfileImageUpdatedResponseDto.java
  src/main/java/com/synergy/backend/domain/member/entity/Attendee.java
  src/main/java/com/synergy/backend/domain/member/repository/RecruiterAttendeeLikeRepository.java
  src/main/java/com/synergy/backend/domain/member/service/AttendeeService.java
  src/main/java/com/synergy/backend/domain/member/service/AttendeeServiceImpl.java
  src/main/java/com/synergy/backend/domain/member/service/RecruiterAttendeeLikeServiceImpl.java
  src/main/java/com/synergy/backend/domain/point/service/PointService.java
  src/main/java/com/synergy/backend/domain/point/service/PointServiceImpl.java
  src/main/java/com/synergy/backend/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/synergy/backend/global/jwt/JwtProvider.java
  src/main/java/com/synergy/backend/global/security/CustomUserDetailsService.java
  src/main/java/com/synergy/backend/global/util/JwtBatchGenerator.java
  src/main/java/com/synergy/backend/global/util/file/exception/EmptyImageFileException.java
  src/main/java/com/synergy/backend/global/util/file/exception/ErrorType.java
  src/main/resources/data-test.sql
  src/main/resources/data.sql
  src/test/java/com/synergy/backend/domain/booth/controller/BoothControllerTest.java
  src/test/java/com/synergy/backend/domain/booth/repository/querydsl/BoothRepositoryImplTest.java
  src/test/java/com/synergy/backend/domain/conference/api/ConferenceControllerTest.java
  src/test/java/com/synergy/backend/domain/member/api/RecruiterControllerTest.java
  src/test/java/com/synergy/backend/domain/member/service/AttendeeServiceImplTest.java
  src/test/java/com/synergy/backend/domain/member/service/AuthServiceImplTest.java
  src/test/java/com/synergy/backend/domain/member/service/RecruiterAttendeeLikeServiceImplTest.java
Labels: feature, refactor, test

#152 test: member, point controller 테스트
  src/main/java/com/synergy/backend/domain/member/api/dto/request/SignupAttendeeRequestDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/RecruiterMyInfoResponseDto.java
  src/main/java/com/synergy/backend/domain/member/service/AttendeeServiceImpl.java
  src/test/java/com/synergy/backend/domain/member/api/AdminControllerTest.java
  src/test/java/com/synergy/backend/domain/member/api/AttendeeControllerTest.java
  src/test/java/com/synergy/backend/domain/member/api/RecruiterControllerTest.java
  src/test/java/com/synergy/backend/domain/point/api/PointControllerTest.java
  src/test/java/com/synergy/backend/module/ControllerTestSupport.java
Labels: test

#153 fix: booth API 전면 수정
  src/main/java/com/synergy/backend/domain/booth/controller/BoothController.java
  src/main/java/com/synergy/backend/domain/booth/controller/BoothDashboardController.java
  src/main/java/com/synergy/backend/domain/booth/controller/BoothVerifyController.java
  src/main/java/com/synergy/backend/domain/booth/dto/BoothDetailResponseDto.java
  src/main/java/com/synergy/backend/domain/booth/dto/BoothResponseDto.java
  src/main/java/com/synergy/backend/domain/booth/dto/boothParticipateDto/BoothParticipateDetailDto.java
  src/main/java/com/synergy/backend/domain/booth/dto/boothParticipateDto/BoothParticipateInterestedTechDto.java
  src/main/java/com/synergy/backend/domain/booth/dto/boothParticipateDto/BoothParticipateRateResDto.java
  src/main/java/com/synergy/backend/domain/booth/dto/boothParticipateDto/BoothParticipationInterestedResponseDto.java
  src/main/java/com/synergy/backend/domain/booth/repository/BoothParticipationRepository.java
  src/main/java/com/synergy/backend/domain/booth/repository/BoothRepository.java
  src/main/java/com/synergy/backend/domain/booth/repository/querydsl/BoothRepositoryCustom.java
  src/main/java/com/synergy/backend/domain/booth/repository/querydsl/BoothRepositoryImpl.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothParticipationService.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothParticipationServiceImpl.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothService.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothServiceImpl.java
  src/main/resources/data.sql
  src/test/java/com/synergy/backend/domain/booth/controller/BoothControllerTest.java
  src/test/java/com/synergy/backend/domain/booth/repository/querydsl/BoothRepositoryImplTest.java
  src/test/java/com/synergy/backend/domain/booth/service/BoothServiceImplTest.java
Labels: fix, feature, refactor

#158 docs: add run tests with coverage
  .github/workflows/CI-CD.yml
Labels: feature

#159 fix: 부스 전달 데이터 수정
  src/main/java/com/synergy/backend/domain/booth/dto/BoothResponseDto.java
  src/main/java/com/synergy/backend/domain/booth/dto/boothParticipateDto/BoothParticipateDetailDto.java
  src/main/java/com/synergy/backend/domain/booth/dto/boothParticipateDto/BoothParticipationInterestedResponseDto.java
  src/main/java/com/synergy/backend/domain/booth/entity/Booth.java
  src/main/java/com/synergy/backend/domain/booth/repository/querydsl/BoothRepositoryImpl.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothParticipationServiceImpl.java
Labels: fix

#161 fix: 부스 등록 시 imageFile에 대한 로직 수정
  src/main/java/com/synergy/backend/domain/booth/service/BoothServiceImpl.java
Labels: fix

#162 docs: update readme
  README.md
  assets/erd.png
Labels: style

#163 fix: 부스 순위 조회 시 0인 값에 대해서 반환하지 않도록 수정
  src/main/java/com/synergy/backend/domain/booth/repository/querydsl/BoothRepositoryImpl.java
Labels: refactor

#165 feat: 컨퍼런스에 대한 사용자 수 조회 기능 구현
  src/main/java/com/synergy/backend/domain/booth/repository/BoothParticipationRepository.java
  src/main/java/com/synergy/backend/domain/booth/repository/querydsl/BoothRepositoryCustom.java
  src/main/java/com/synergy/backend/domain/booth/repository/querydsl/BoothRepositoryImpl.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothParticipationServiceImpl.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothServiceImpl.java
  src/main/java/com/synergy/backend/domain/conference/api/ConferenceController.java
  src/main/java/com/synergy/backend/domain/conference/dto/response/ConferenceAttendeeInfoResDto.java
  src/main/java/com/synergy/backend/domain/conference/service/ConferenceService.java
  src/main/java/com/synergy/backend/domain/conference/service/ConferenceServiceImpl.java
  src/main/java/com/synergy/backend/domain/member/repository/AttendeeRepository.java
  src/main/java/com/synergy/backend/domain/session/repository/AttendeeSessionRepository.java
  src/main/java/com/synergy/backend/domain/session/repository/sessionRepository/SessionCustomRepository.java
  src/main/java/com/synergy/backend/domain/session/repository/sessionRepository/SessionCustomRepositoryImpl.java
Labels: fix

#167 fix: 부스세션 api 반환 데이터 수정
  src/main/java/com/synergy/backend/domain/booth/dto/boothParticipateDto/BoothParticipationInterestedResponseDto.java
  src/main/java/com/synergy/backend/domain/booth/entity/Booth.java
  src/main/java/com/synergy/backend/domain/booth/repository/querydsl/BoothRepositoryImpl.java
  src/main/java/com/synergy/backend/domain/booth/service/BoothServiceImpl.java
  src/main/java/com/synergy/backend/domain/session/dto/sessionparticipateDto/SessionParticipateRateDetailResDto.java
  src/main/java/com/synergy/backend/domain/session/entity/Session.java
  src/main/java/com/synergy/backend/domain/session/repository/sessionRepository/SessionCustomRepositoryImpl.java
  src/main/java/com/synergy/backend/domain/session/service/SessionServiceImpl.java
  src/test/java/com/synergy/backend/domain/booth/entity/BoothTest.java
  src/test/java/com/synergy/backend/domain/booth/service/BoothServiceImplTest.java
Labels: fix

#169 fix: Register ResposneDto changed
  src/main/java/com/synergy/backend/domain/member/api/AuthController.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/SignupAttendeeResponseDto.java
  src/main/java/com/synergy/backend/domain/member/api/dto/resposne/TokenResponseDto.java
  src/main/java/com/synergy/backend/domain/member/service/AuthService.java
  src/main/java/com/synergy/backend/domain/member/service/AuthServiceImpl.java
  src/test/java/com/synergy/backend/domain/member/service/AuthServiceImplTest.java
Labels: fix

#172 feat: 부스 삭제
  .gitignore
  src/main/java/com/synergy/backend/domain/booth/entity/Booth.java
  src/main/java/com/synergy/backend/global/token/CookieUtils.java
  src/main/resources/application.yml
  src/test/java/com/synergy/backend/domain/booth/service/BoothParticipationServiceImplTest.java
Labels: fix, test
